driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || "current" %>

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec

platforms:
- name: debian-7
  driver:
    image: dokken/debian-7
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-8
  driver:
    image: dokken/debian-8
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6

- name: centos-7
  driver:
    image: dokken/centos-7

- name: fedora-latest
  driver:
    image: dokken/fedora-latest

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
